"""Seed 4 realistic, fully-finalized example PA requests into the
`pa_requests` table for the four bundled fictitious patients, spanning
different points in a request's real-world lifecycle (drafted-and-ready,
submitted, more-info-requested, and rejected-during-review).

These are hand-authored (not generated by a live LLM call, to keep this
repo's setup free to run), but they are exactly the kind of output a real
run of `extract_clinical_summary_node` / `match_policy_criteria_node` /
`draft_pa_request_node` against the corresponding referral in
`sample-data/referrals/` would plausibly produce, each carrying a realistic
staff decision and a status history demonstrating the "PA Request Tracking"
page's core value: seeing where each request stands without re-reading the
whole chart.

Run with:
    python -m scripts.seed_examples

Requires `scripts/seed_patients.py` to have already run (the patients this
script attaches PA requests to must already exist).
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.db.models import PARequest
from app.db.session import SessionLocal


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _trace(base: datetime, node: str, minutes: float, summary: str) -> dict:
    return {"node": node, "timestamp": _iso(base + timedelta(minutes=minutes)), "summary": summary}


def _seed_one(
    *,
    request_id: str,
    patient_id: str,
    payer_name: str,
    original_filename: str,
    clinical_summary: dict,
    criteria_checklist: list,
    draft_form: dict,
    human_decision: str,
    human_feedback: str,
    days_ago: float,
    review_delay_minutes: float,
    post_finalize_events: list[tuple[float, str, str]],  # (days_after_finalize, status, note)
) -> None:
    with SessionLocal() as db:
        if db.get(PARequest, request_id) is not None:
            print(f"[skip] PA request {request_id!r} already seeded")
            return

    t0 = datetime.now(timezone.utc) - timedelta(days=days_ago)

    if human_decision == "reject":
        final_status, status = "rejected", "rejected"
    else:
        final_status = "corrected_and_ready" if human_decision == "correct" else "ready_to_submit"
        status = "ready_to_submit"

    finalize_time = t0 + timedelta(minutes=review_delay_minutes + 0.1)
    trace = [
        _trace(t0, "ingest", 0.0, f"Detected plain-text chart excerpt; read {original_filename}."),
        _trace(
            t0,
            "extract_clinical_summary",
            0.4,
            f"Extracted requested service {clinical_summary.get('requested_service', '')!r} for diagnosis "
            f"{clinical_summary.get('diagnosis', '')!r}.",
        ),
        _trace(
            t0,
            "match_policy_criteria",
            0.8,
            f"Draft assessment for staff review: "
            f"{sum(1 for c in criteria_checklist if c['status'] == 'met')}/{len(criteria_checklist)} of "
            f"{payer_name}'s criteria appear met based on the chart excerpt (not a coverage decision).",
        ),
        _trace(t0, "draft_pa_request", 1.1, "Drafted PA request form with LLM-assembled codes and clinical justification."),
        _trace(t0, "staff_review", review_delay_minutes, f"Staff decision={human_decision} | {human_feedback[:200]}"),
        _trace(t0, "finalize", review_delay_minutes + 0.1, f"PA request draft finalized with status={final_status}."),
    ]

    status_history = []
    if status != "rejected":
        status_history.append({"status": status, "timestamp": _iso(finalize_time), "note": "Drafting complete."})
    for days_after, next_status, note in post_finalize_events:
        status_history.append(
            {"status": next_status, "timestamp": _iso(finalize_time + timedelta(days=days_after)), "note": note}
        )
        status = next_status

    state_snapshot = {
        "clinical_summary": clinical_summary,
        "criteria_checklist": criteria_checklist,
        "draft_form": draft_form,
        "human_decision": human_decision,
        "human_feedback": human_feedback,
        "final_status": final_status,
        "status": status,
    }

    pa_request = PARequest(
        id=request_id,
        patient_id=patient_id,
        payer_name=payer_name,
        original_filename=original_filename,
        status=status,
        final_status=final_status,
        clinical_summary=clinical_summary,
        criteria_checklist=criteria_checklist,
        draft_form=draft_form,
        trace=trace,
        state_snapshot=state_snapshot,
        status_history=status_history,
        error=None,
        created_at=t0,
        updated_at=(
            finalize_time
            if not post_finalize_events
            else finalize_time + timedelta(days=post_finalize_events[-1][0])
        ),
    )
    with SessionLocal() as db:
        db.add(pa_request)
        db.commit()
    print(f"[seeded] PA request {request_id!r} ({original_filename}, status={status})")


def seed() -> None:
    # ---------------------------------------------------------------
    # Jordan Blake -- lumbar MRI, criteria clearly met, staff approved as
    # drafted. Status: ready_to_submit (not yet submitted to the payer).
    # ---------------------------------------------------------------
    jordan_summary = {
        "diagnosis": "Chronic low back pain with left L5-S1 radiculopathy",
        "requested_service": "Lumbar spine MRI without contrast",
        "duration_of_symptoms": "Approximately 10 weeks",
        "prior_treatments_tried": [
            "6-week course of physical therapy (12 visits) focused on core strengthening and lumbar stabilization",
            "Naproxen 500 mg twice daily for 8 weeks",
            "Short course of cyclobenzaprine, discontinued due to drowsiness",
            "Activity modification (avoiding heavy lifting)",
        ],
        "exam_findings": [
            "Positive straight leg raise on the left at 40 degrees",
            "Decreased sensation to light touch along the lateral left foot (L5-S1 distribution)",
            "Left ankle plantarflexion strength 4/5 compared to 5/5 on the right",
            "Deep tendon reflexes symmetric",
        ],
        "relevant_history": [
            "Lumbar spine X-ray obtained 3 weeks ago showed mild degenerative disc space narrowing at L5-S1 but no acute findings; did not explain radicular symptoms",
            "No bowel or bladder dysfunction, no saddle anesthesia, no fever, no unexplained weight loss, no history of cancer",
        ],
        "referring_provider_name": "Dr. Alicia Munoz, MD",
    }
    jordan_criteria = [
        {"criterion_id": "meridian-health-plan-a", "criterion_text": "Low back pain symptoms have been present for greater than 6 weeks.", "status": "met", "evidence": "Pain began approximately 10 weeks ago."},
        {"criterion_id": "meridian-health-plan-b", "criterion_text": "Conservative treatment has been attempted for at least 6 weeks without adequate improvement.", "status": "met", "evidence": "Completed a 6-week, 12-visit PT course and 8 weeks of naproxen with only mild, temporary relief."},
        {"criterion_id": "meridian-health-plan-c", "criterion_text": "A documented neurological deficit OR a red-flag symptom is present.", "status": "met", "evidence": "Decreased sensation along the lateral left foot and left ankle plantarflexion strength 4/5 versus 5/5 on the right."},
        {"criterion_id": "meridian-health-plan-d", "criterion_text": "A prior X-ray did not adequately explain symptoms, or no X-ray was performed.", "status": "met", "evidence": "X-ray from 3 weeks ago showed only mild degenerative changes and did not explain the radicular symptoms."},
        {"criterion_id": "meridian-health-plan-e", "criterion_text": "MRI findings are expected to change management.", "status": "met", "evidence": "Provider documented MRI is being requested to inform surgical vs. non-surgical referral or injection planning."},
    ]
    jordan_draft = {
        "patient_name": "Jordan Blake",
        "patient_dob": "1979-03-14",
        "patient_member_id": "MHP-5521309",
        "payer_name": "Meridian Health Plan",
        "provider_name": "Dr. Alicia Munoz, MD",
        "provider_npi": "1447920033",
        "requested_service": "Lumbar spine MRI without contrast",
        "service_code": "72148",
        "diagnosis": "Chronic low back pain with left L5-S1 radiculopathy",
        "diagnosis_code": "M54.16",
        "clinical_justification": (
            "Patient reports 10 weeks of low back pain with radiation into the left leg. Conservative "
            "treatment including 6 weeks of physical therapy and 8 weeks of NSAID therapy has not "
            "produced adequate improvement. Exam shows a positive straight leg raise, decreased "
            "sensation in an L5-S1 distribution, and mild ankle plantarflexion weakness, consistent with "
            "a neurological deficit. A recent X-ray did not explain these findings. Based on the chart, "
            "criteria (a) symptom duration, (b) failed conservative treatment, (c) neurological deficit, "
            "(d) inconclusive prior imaging, and (e) anticipated change in management all appear met. "
            "This is a draft for staff review and does not represent a coverage determination, which "
            "rests with the payer."
        ),
    }
    _seed_one(
        request_id="seed-lumbar-mri-jordan-blake",
        patient_id="jordan-blake",
        payer_name="Meridian Health Plan",
        original_filename="lumbar_mri_referral_jordan_blake.txt",
        clinical_summary=jordan_summary,
        criteria_checklist=jordan_criteria,
        draft_form=jordan_draft,
        human_decision="approve",
        human_feedback="Criteria clearly met; approving draft as written.",
        days_ago=5,
        review_delay_minutes=22,
        post_finalize_events=[],
    )

    # ---------------------------------------------------------------
    # Casey Rivera -- adalimumab request, criteria met, staff approved and
    # the request has already been submitted to the payer.
    # ---------------------------------------------------------------
    casey_summary = {
        "diagnosis": "Active psoriatic arthritis",
        "requested_service": "Adalimumab (Humira) 40 mg subcutaneous injection every other week",
        "duration_of_symptoms": "Diagnosis established 8 months ago; current flare ongoing despite treatment",
        "prior_treatments_tried": [
            "Methotrexate 15 mg weekly, titrated to 20 mg weekly, for 4 months with folic acid supplementation, discontinued due to inadequate response",
            "NSAIDs, only partially effective",
        ],
        "exam_findings": [
            "6 tender and 4 swollen joints (bilateral MCPs and PIPs)",
            "Dactylitis in the right third finger",
            "Enthesitis tenderness at the right Achilles insertion",
            "CRP 18 mg/L (elevated), ESR 32 mm/hr (elevated)",
        ],
        "relevant_history": [
            "QuantiFERON-TB Gold negative",
            "Hepatitis B surface antigen and core antibody negative",
        ],
        "referring_provider_name": "Dr. Wen Zhao, MD",
    }
    casey_criteria = [
        {"criterion_id": "cascade-community-health-a", "criterion_text": "Confirmed diagnosis of psoriatic arthritis by a rheumatologist or equivalent.", "status": "met", "evidence": "Diagnosis established by rheumatology 8 months ago with imaging showing erosive changes."},
        {"criterion_id": "cascade-community-health-b", "criterion_text": "Inadequate response to at least one DMARD for a minimum of 3 months.", "status": "met", "evidence": "Methotrexate 20 mg weekly for 4 months with inadequate response."},
        {"criterion_id": "cascade-community-health-c", "criterion_text": "Active disease documented at the time of request.", "status": "met", "evidence": "6 tender/4 swollen joints, dactylitis, enthesitis, and elevated CRP/ESR documented today."},
        {"criterion_id": "cascade-community-health-d", "criterion_text": "Screened for latent TB and hepatitis B prior to starting therapy.", "status": "met", "evidence": "QuantiFERON-TB Gold and hepatitis B screening both performed last week and negative."},
        {"criterion_id": "cascade-community-health-e", "criterion_text": "Plan to monitor for infection risk and treatment response documented.", "status": "met", "evidence": "Provider documented plans to monitor CBC, CMP, inflammatory markers, and infection signs."},
    ]
    casey_draft = {
        "patient_name": "Casey Rivera",
        "patient_dob": "1988-11-02",
        "patient_member_id": "CCH-7740221",
        "payer_name": "Cascade Community Health",
        "provider_name": "Dr. Wen Zhao, MD",
        "provider_npi": "1982043117",
        "requested_service": "Adalimumab (Humira) 40 mg subcutaneous injection every other week",
        "service_code": "J0135",
        "diagnosis": "Active psoriatic arthritis",
        "diagnosis_code": "L40.50",
        "clinical_justification": (
            "Patient has a confirmed diagnosis of psoriatic arthritis with an inadequate response to a "
            "4-month adequate trial of methotrexate. Active disease is documented today via tender/"
            "swollen joint counts, dactylitis, enthesitis, and elevated inflammatory markers. Required "
            "TB and hepatitis B screening has been completed and is negative, and a monitoring plan is "
            "in place. Based on the chart, all five of the payer's listed criteria appear met. This is a "
            "draft for staff review and does not represent a coverage determination, which rests with "
            "the payer."
        ),
    }
    _seed_one(
        request_id="seed-adalimumab-casey-rivera",
        patient_id="casey-rivera",
        payer_name="Cascade Community Health",
        original_filename="specialty_medication_adalimumab_casey_rivera.txt",
        clinical_summary=casey_summary,
        criteria_checklist=casey_criteria,
        draft_form=casey_draft,
        human_decision="approve",
        human_feedback="All criteria met; approved and ready to submit.",
        days_ago=9,
        review_delay_minutes=15,
        post_finalize_events=[(1.0, "submitted", "Submitted to Cascade Community Health via payer portal.")],
    )

    # ---------------------------------------------------------------
    # Morgan Ellis -- physical therapy extension, mostly met but one
    # criterion unclear; staff approved with a note, submitted, and the
    # payer has since asked for more information.
    # ---------------------------------------------------------------
    morgan_summary = {
        "diagnosis": "Status post right knee arthroscopic partial meniscectomy, functional deficit",
        "requested_service": "Outpatient physical therapy extension, 8 additional visits",
        "duration_of_symptoms": "7 weeks post-surgery; 3 weeks into initial physical therapy",
        "prior_treatments_tried": [
            "Initial authorization of 6 physical therapy visits, all completed over 3 weeks",
        ],
        "exam_findings": [
            "Right knee active range of motion improved from 0-95 to 0-118 degrees",
            "Quadriceps strength improved from 3/5 to 4/5",
            "Pain with stairs decreased from 7/10 to 4/10",
            "Walking distance improved from 1 block to 4 blocks without a cane",
        ],
        "relevant_history": [
            "Functional goal: return to full duty as a warehouse supervisor requiring ladder climbing, repeated squatting, and 30 minutes of continuous walking",
            "Most recent visit note does not restate a numeric pain score or fresh strength grade for that specific session",
        ],
        "referring_provider_name": "Jamie Sutton, PT, DPT",
    }
    morgan_criteria = [
        {"criterion_id": "beacon-preferred-insurance-a", "criterion_text": "Initial authorized visits completed with a progress note available.", "status": "met", "evidence": "All 6 initially authorized visits completed over 3 weeks; progress note provided."},
        {"criterion_id": "beacon-preferred-insurance-b", "criterion_text": "Objective, measurable functional improvement documented.", "status": "met", "evidence": "Range of motion, strength, pain score, and walking distance all show measurable improvement."},
        {"criterion_id": "beacon-preferred-insurance-c", "criterion_text": "A specific functional goal not yet met is documented.", "status": "met", "evidence": "Patient not yet able to squat below 90 degrees without pain or reliably navigate stairs, needed for the stated return-to-work goal."},
        {"criterion_id": "beacon-preferred-insurance-d", "criterion_text": "Updated plan of care with estimated additional visits and timeframe documented.", "status": "met", "evidence": "Therapist documented an updated plan: 8 additional visits over 4 weeks, reassessing at visit 4."},
        {"criterion_id": "beacon-preferred-insurance-e", "criterion_text": "No evidence of a 2+ visit plateau without treatment adjustment.", "status": "unclear", "evidence": "Improvement has been steady per the note, but the most recent visit does not restate a fresh numeric pain score or strength grade, so the single most current data point is incomplete."},
    ]
    morgan_draft = {
        "patient_name": "Morgan Ellis",
        "patient_dob": "1965-06-21",
        "patient_member_id": "BPI-3391847",
        "payer_name": "Beacon Preferred Insurance",
        "provider_name": "Jamie Sutton, PT, DPT",
        "provider_npi": "1265590042",
        "requested_service": "Outpatient physical therapy extension, 8 additional visits",
        "service_code": "97110",
        "diagnosis": "Pain in right knee",
        "diagnosis_code": "M25.561",
        "clinical_justification": (
            "Patient has completed the initial 6-visit physical therapy authorization following right "
            "knee arthroscopic partial meniscectomy, with documented, measurable improvement in range of "
            "motion, strength, pain, and walking distance. A specific remaining functional goal (return "
            "to full-duty work requiring squatting, ladder climbing, and sustained walking) is documented, "
            "along with an updated plan of care requesting 8 additional visits over 4 weeks. Whether "
            "progress has plateaued is unclear from the most recent visit note alone, which does not "
            "restate a fresh pain score or strength grade for that specific session -- staff should "
            "confirm this with the treating therapist. This is a draft for staff review and does not "
            "represent a coverage determination, which rests with the payer."
        ),
    }
    _seed_one(
        request_id="seed-pt-extension-morgan-ellis",
        patient_id="morgan-ellis",
        payer_name="Beacon Preferred Insurance",
        original_filename="pt_extension_request_morgan_ellis.txt",
        clinical_summary=morgan_summary,
        criteria_checklist=morgan_criteria,
        draft_form=morgan_draft,
        human_decision="correct",
        human_feedback="Added a note asking the therapist to confirm the most recent visit's pain score and strength grade before submission; approved to submit alongside that clarification.",
        days_ago=14,
        review_delay_minutes=35,
        post_finalize_events=[
            (1.0, "submitted", "Submitted to Beacon Preferred Insurance via fax per payer instructions."),
            (6.0, "more_info_requested", "Payer requested the most recent visit's specific pain score and strength grade before making a determination."),
        ],
    )

    # ---------------------------------------------------------------
    # Sam Okafor -- lumbar MRI requested too early; criteria largely unmet,
    # staff rejected the draft rather than submit it prematurely.
    # ---------------------------------------------------------------
    sam_summary = {
        "diagnosis": "Acute, uncomplicated mechanical low back pain",
        "requested_service": "Lumbar spine MRI without contrast",
        "duration_of_symptoms": "12 days",
        "prior_treatments_tried": [
            "Over-the-counter ibuprofen 400 mg as needed, taken intermittently for about a week",
        ],
        "exam_findings": [
            "Mild paraspinal tenderness in the lumbar region",
            "Straight leg raise negative bilaterally",
            "Sensation intact throughout both lower extremities",
            "Strength 5/5 throughout, reflexes symmetric and normal",
        ],
        "relevant_history": [
            "No prior lumbar spine imaging has been obtained",
            "No bowel or bladder dysfunction, no saddle anesthesia, no fever, no unexplained weight loss, no history of cancer",
            "Physical therapy referral started today but not yet begun",
        ],
        "referring_provider_name": "Dr. Alicia Munoz, MD",
    }
    sam_criteria = [
        {"criterion_id": "meridian-health-plan-a", "criterion_text": "Low back pain symptoms have been present for greater than 6 weeks.", "status": "unmet", "evidence": "Symptoms began only 12 days ago."},
        {"criterion_id": "meridian-health-plan-b", "criterion_text": "Conservative treatment has been attempted for at least 6 weeks without adequate improvement.", "status": "unmet", "evidence": "Only intermittent OTC ibuprofen for about a week; no formal physical therapy or structured home exercise program attempted yet, and PT was just referred today."},
        {"criterion_id": "meridian-health-plan-c", "criterion_text": "A documented neurological deficit OR a red-flag symptom is present.", "status": "unmet", "evidence": "Straight leg raise negative, sensation and strength intact, no red-flag symptoms documented."},
        {"criterion_id": "meridian-health-plan-d", "criterion_text": "A prior X-ray did not adequately explain symptoms, or no X-ray was performed.", "status": "met", "evidence": "No prior lumbar spine imaging has been obtained."},
        {"criterion_id": "meridian-health-plan-e", "criterion_text": "MRI findings are expected to change management.", "status": "unclear", "evidence": "Note states guideline-concordant care would start with conservative treatment first; no documentation that MRI findings would change management at this stage."},
    ]
    sam_draft = {
        "patient_name": "Sam Okafor",
        "patient_dob": "1992-01-09",
        "patient_member_id": "MHP-6602218",
        "payer_name": "Meridian Health Plan",
        "provider_name": "Dr. Alicia Munoz, MD",
        "provider_npi": "1447920033",
        "requested_service": "Lumbar spine MRI without contrast",
        "service_code": "72148",
        "diagnosis": "Acute, uncomplicated mechanical low back pain",
        "diagnosis_code": "M54.50",
        "clinical_justification": (
            "Patient presents with 12 days of low back pain after a hiking trip, without radiation, "
            "neurological deficit, or red-flag symptoms, and has not yet completed a course of "
            "conservative treatment (only intermittent OTC ibuprofen; physical therapy was referred "
            "today but not yet started). Based on the chart, most of the payer's medical-necessity "
            "criteria for lumbar MRI do not currently appear met. This is a draft for staff review and "
            "does not represent a coverage determination, which rests with the payer."
        ),
    }
    _seed_one(
        request_id="seed-lumbar-mri-sam-okafor",
        patient_id="sam-okafor",
        payer_name="Meridian Health Plan",
        original_filename="lumbar_mri_referral_sam_okafor.txt",
        clinical_summary=sam_summary,
        criteria_checklist=sam_criteria,
        draft_form=sam_draft,
        human_decision="reject",
        human_feedback=(
            "Rejecting this draft rather than submitting -- symptom duration and conservative treatment "
            "criteria are not yet met. Recommend the office complete the physical therapy referral "
            "already placed and resubmit if symptoms persist beyond 6 weeks."
        ),
        days_ago=2,
        review_delay_minutes=12,
        post_finalize_events=[],
    )

    print("[done] seeded 4 example PA requests across jordan-blake / casey-rivera / morgan-ellis / sam-okafor")


if __name__ == "__main__":
    seed()
